name: Release on Push

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          TAG_PREFIX="v"
          RELEASE_VERSION=$(git rev-parse --short $GITHUB_SHA)
          RELEASE_INFO="{\"version\": \"$TAG_PREFIX$RELEASE_VERSION\", \"sha\": \"$GITHUB_SHA\"}"
          echo "Release version: $TAG_PREFIX$RELEASE_VERSION"
          echo "Release info in JSON format: $RELEASE_INFO"
          
          # Save release info to a JSON file in the root directory
          echo $RELEASE_INFO > release_info.json
          ls -sh




          # Create a release using GitHub CLI
          #gh release create "$TAG_PREFIX$RELEASE_VERSION" ./path/to/release/artifact --notes "$RELEASE_INFO"

