on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run release-on-push action
        run: npm run release-on-push
        env:
          TAG_PREFIX: "v"
          RELEASE_VERSION: ${{ github.sha }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: ./path/to/release/artifact
